framecount = 0

#Main
GAME_WIDTH = 104
GAME_HEIGHT = 140
FPS = 30
TITLE = "Space Survivor"

PLAYER_STARTING_X = 48
PLAYER_STARTING_Y = 120
PLAYER_HP = 3
PLAYER_IFRAMES = 30
PLAYER_DEATHFREEZE_DURATION = 50

ASTEROID_COOLDOWN = 10
ASTEROID_OFFSET_FROM_BORDERS = 2

BULLET_DAMAGE = 1
BULLET_COOLDOWN = 3
MAGNET_RANGE = 5

ASTEROID_TYPE_1 = 0
ASTEROID_TYPE_2 = 1
ASTEROID_TYPE_3 = 2

ASTEROID_TYPE_1_SIZE = 8
ASTEROID_TYPE_2_SIZE = 16
ASTEROID_TYPE_3_SIZE = 32

#Sounds
CHANNEL_1 = 0
CHANNEL_2 = 1
CHANNEL_3 = 2
CHANNEL_4 = 3

BULLET_SOUND = 0
IMPACT_SOUND = 1
PICKUP_SOUND = 2
PLAYER_DEATH_SOUND = 3